-- Generated by matugen. Do not edit: change ~/.config/matugen/templates/hyprland.lua instead
hl.config({
    general = {
        col = {
            -- Thin solid accent on the focused window; inactive windows show no border
            active_border   = "rgba({{colors.primary.default.hex_stripped}}ff)",
            inactive_border = "rgba(00000000)",
        },
    },
    misc = {
        -- Shown where no wallpaper is drawn, e.g. after hyprpaper stops at shutdown
        background_color = "rgba({{colors.surface.default.hex_stripped}}ff)",
    },
})
