-- Generated by matugen. Do not edit: change ~/.config/matugen/templates/hyprland.lua instead
hl.config({
    general = {
        col = {
            -- Thin solid accent on the focused window; inactive windows show no border
            active_border   = "rgba(aec6ffff)",
            inactive_border = "rgba(00000000)",
        },
    },
})
